AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - './makanai.gemspec'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/makanai/rake_tasks.rb'

Style/ParallelAssignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
