AllCops:
  NewCops: enable
  Exclude:
    - "./makanai.gemspec"
    - "vendor/**/*"

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/makanai/rake_tasks.rb"

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 90

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - "spec/**/*"
