AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - './makanai.gemspec'

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/makanai/rake_tasks.rb'

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/LineLength:
  Max: 90

Layout/EmptyLineAfterGuardClause:
  Enabled: false
