AllCops:
  TargetRubyVersion: 2.6.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/ClassLength:
  Max: 120

Style/ParallelAssignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

