---
language: ruby
cache: bundler
services:
  - postgresql
  - mysql
rvm:
  - 2.6.6
  - 2.7.1
  - ruby-head
os:
  - linux
before_install:
  - gem install bundler -v 2.1.4
  - mysql -e 'CREATE DATABASE IF NOT EXISTS makanai;'
before_script:
  - psql -c "create user makanai WITH PASSWORD 'password';" -U postgres
  - psql -c 'create database makanai;' -U postgres
script:
  - bundle exec rubocop --parallel
  - bundle exec rspec
jobs:
  allow_failures:
    - rvm: ruby-head
