---
language: ruby
cache: bundler
services:
  - postgresql
  - mysql
rvm:
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - ruby-head
os:
  - linux
before_install:
  - gem install bundler -v 2.2.3
  - mysql -e 'CREATE DATABASE IF NOT EXISTS makanai;'
before_script:
  - psql -c "create user makanai WITH PASSWORD 'password';" -U postgres
  - psql -c 'create database makanai;' -U postgres
script:
  - bundle exec rubocop --parallel
  - bundle exec rspec
jobs:
  allow_failures:
    - rvm: ruby-head
