---
sudo: false
language: ruby
cache: bundler
services:
  - postgresql
  - mysql
rvm:
  - 2.6.5
  - 2.7.0
  - ruby-head
before_install:
  - gem install bundler -v 2.1.2
  - mysql -e 'CREATE DATABASE IF NOT EXISTS makanai;'
before_script:
  - psql -c 'create database makanai;' -U postgres
matrix:
  allow_failures:
    - rvm: ruby-head
